import { ethers } from "hardhat";
import type { Covenant, MockUSDC } from "../typechain-types";
import type { SwarmWallet } from "./wallets";
import { runWrite, runRead, type TxOutcome } from "./txRunner";
import type { SwarmMetrics } from "./metrics";

// ApprovalModel enum values from Covenant.sol.
const APPROVAL_MODEL = { DesignatedReviewers: 0, LeadDonor: 1 } as const;
// CampaignKind enum values.
const CAMPAIGN_KINDS = [0, 1, 2, 3] as const;

export interface CampaignInfo {
  id: bigint;
  creatorIndex: number;
  approvalModel: 0 | 1;
  reviewerIndices: number[];
  milestoneCount: number;
}

export interface World {
  campaigns: CampaignInfo[];
  reviewerWallets: SwarmWallet[];
}

export interface ScenarioContext {
  wallet: SwarmWallet;
  covenant: Covenant;
  usdc: MockUSDC;
  covenantAddress: string;
  world: World;
  rng: () => number;
  maxRetries: number;
  metrics: SwarmMetrics;
}

function pick<T>(items: T[], rng: () => number): T {
  return items[Math.floor(rng() * items.length)];
}

function randomInt(rng: () => number, min: number, max: number): number {
  return Math.floor(min + rng() * (max - min + 1));
}

function usdc6(whole: number): bigint {
  return ethers.parseUnits(whole.toFixed(2), 6);
}

function recordWrite(ctx: ScenarioContext, scenario: string, outcome: TxOutcome) {
  ctx.metrics.record({
    scenario,
    walletIndex: ctx.wallet.index,
    role: ctx.wallet.role,
    ok: outcome.ok,
    isRead: false,
    durationMs: outcome.durationMs,
    gasUsed: outcome.gasUsed,
    revertReason: outcome.revertReason,
    errorMessage: outcome.errorMessage,
    retries: outcome.retries,
  });
}

function recordRead(ctx: ScenarioContext, scenario: string, outcome: TxOutcome) {
  ctx.metrics.record({
    scenario,
    walletIndex: ctx.wallet.index,
    role: ctx.wallet.role,
    ok: outcome.ok,
    isRead: true,
    durationMs: outcome.durationMs,
    errorMessage: outcome.errorMessage,
    retries: 0,
  });
}

// ---------------------------------------------------------------------------
// Creator scenarios
// ---------------------------------------------------------------------------

export async function createCampaignScenario(ctx: ScenarioContext) {
  const { wallet, covenant, rng } = ctx;
  const milestoneCount = randomInt(rng, 2, 3);
  const milestoneAmount = randomInt(rng, 20, 100);

  // PlatformOperator campaigns can never be reviewed by swarm wallets (the
  // owner is the deployer, outside the swarm), so we only generate the two
  // models the swarm can actually service end-to-end.
  const reviewerPool = ctx.world.reviewerWallets.filter(r => r.wallet.address !== wallet.wallet.address);
  const useDesignated = rng() < 0.55 && reviewerPool.length > 0;
  const chosenReviewers = useDesignated
    ? Array.from(
        new Set(Array.from({ length: randomInt(rng, 1, 3) }, () => pick(reviewerPool, rng).index)),
      )
    : [];

  const approval = useDesignated
    ? {
        model: APPROVAL_MODEL.DesignatedReviewers,
        reviewers: chosenReviewers.map(
          idx => ctx.world.reviewerWallets.find(r => r.index === idx)!.wallet.address,
        ),
        threshold: 1,
      }
    : { model: APPROVAL_MODEL.LeadDonor, reviewers: [], threshold: 1 };

  const items = Array.from({ length: milestoneCount }, (_, i) => ({
    criteria: {
      title: `Milestone ${i + 1}`,
      successDefinition: "Synthetic load-test milestone — success is scripted, not evaluated.",
      reportingPeriod: "once",
      expectedMetrics: "",
      requiredProof: "synthetic evidence",
      proofDeadline: 0,
    },
    amount: usdc6(milestoneAmount),
  }));

  const suffix = randomInt(rng, 100000, 999999);
  const outcome = await runWrite(
    () =>
      covenant
        .connect(wallet.wallet)
        .createCampaign(
          `Swarm Campaign ${wallet.index}-${suffix}`,
          "Synthetic campaign generated by the Covenant wallet-swarm load test.",
          pick(CAMPAIGN_KINDS, rng),
          approval,
          items,
        ),
    ctx.maxRetries,
  );
  recordWrite(ctx, "createCampaign", outcome);

  if (outcome.ok) {
    // Re-derive the new campaign id from campaignCount rather than parsing
    // logs — cheaper, and campaignCount is monotonic/authoritative.
    const count = await ctx.covenant.campaignCount();
    const id = count - 1n;
    ctx.world.campaigns.push({
      id,
      creatorIndex: wallet.index,
      approvalModel: useDesignated ? 0 : 1,
      reviewerIndices: chosenReviewers,
      milestoneCount,
    });
  }
}

export async function submitProofScenario(ctx: ScenarioContext) {
  const own = ctx.world.campaigns.filter(c => c.creatorIndex === ctx.wallet.index);
  if (own.length === 0) return;
  const target = pick(own, ctx.rng);

  const campaign = await ctx.covenant.getCampaign(target.id);
  if (!campaign.active || campaign.currentMilestone >= BigInt(campaign.milestoneCount)) return;

  const milestone = await ctx.covenant.getMilestone(target.id, campaign.currentMilestone);
  const state = Number(milestone.state);
  const isPendingOrRevise = state === 0 || state === 2;
  const funded = campaign.totalReleased + milestone.amount <= campaign.totalRaised;
  if (!isPendingOrRevise || !funded) return;

  const summary = `Synthetic proof package for milestone ${campaign.currentMilestone} (load test)`;
  const manifestHash = ethers.keccak256(ethers.toUtf8Bytes(`${target.id}-${Date.now()}-${ctx.rng()}`));

  const outcome = await runWrite(
    () => ctx.covenant.connect(ctx.wallet.wallet).submitProof(target.id, summary, manifestHash, ""),
    ctx.maxRetries,
  );
  recordWrite(ctx, "submitProof", outcome);
}

export async function cancelCampaignScenario(ctx: ScenarioContext) {
  const own = ctx.world.campaigns.filter(c => c.creatorIndex === ctx.wallet.index);
  if (own.length === 0) return;
  const target = pick(own, ctx.rng);
  const campaign = await ctx.covenant.getCampaign(target.id);
  if (!campaign.active) return;

  const outcome = await runWrite(
    () => ctx.covenant.connect(ctx.wallet.wallet).cancelCampaign(target.id),
    ctx.maxRetries,
  );
  recordWrite(ctx, "cancelCampaign", outcome);
}

// ---------------------------------------------------------------------------
// Donor scenarios
// ---------------------------------------------------------------------------

export async function donateScenario(ctx: ScenarioContext) {
  if (ctx.world.campaigns.length === 0) return;
  const target = pick(ctx.world.campaigns, ctx.rng);
  if (target.creatorIndex === ctx.wallet.index) return; // creators can't donate to their own campaign

  const campaign = await ctx.covenant.getCampaign(target.id);
  if (!campaign.active) return;
  const room = campaign.goalAmount - campaign.totalRaised;
  if (room <= 0n) return;
  const failed = await ctx.covenant.milestoneFailed(target.id);
  if (failed) return;

  const cap = room < usdc6(20) ? room : usdc6(randomInt(ctx.rng, 1, 20));
  const amount = cap <= 0n ? room : cap;

  const allowance = await ctx.usdc.allowance(ctx.wallet.wallet.address, ctx.covenantAddress);
  if (allowance < amount) {
    const approveOutcome = await runWrite(
      () => ctx.usdc.connect(ctx.wallet.wallet).approve(ctx.covenantAddress, ethers.MaxUint256),
      ctx.maxRetries,
    );
    recordWrite(ctx, "approveUsdc", approveOutcome);
    if (!approveOutcome.ok) return;
  }

  const outcome = await runWrite(
    () => ctx.covenant.connect(ctx.wallet.wallet).donate(target.id, amount),
    ctx.maxRetries,
  );
  recordWrite(ctx, "donate", outcome);
}

export async function claimRefundScenario(ctx: ScenarioContext) {
  if (ctx.world.campaigns.length === 0) return;
  const target = pick(ctx.world.campaigns, ctx.rng);
  const refundable = await ctx.covenant.refundOf(target.id, ctx.wallet.wallet.address);
  if (refundable <= 0n) return;

  const outcome = await runWrite(
    () => ctx.covenant.connect(ctx.wallet.wallet).claimRefund(target.id),
    ctx.maxRetries,
  );
  recordWrite(ctx, "claimRefund", outcome);
}

// ---------------------------------------------------------------------------
// Reviewer scenarios
// ---------------------------------------------------------------------------

export async function reviewProofScenario(ctx: ScenarioContext) {
  if (ctx.world.campaigns.length === 0) return;
  // Sample a handful of campaigns rather than scanning all of them — this
  // wallet is only ever authorized on a small subset.
  const sample = Array.from({ length: Math.min(5, ctx.world.campaigns.length) }, () =>
    pick(ctx.world.campaigns, ctx.rng),
  );

  for (const target of sample) {
    const isReviewer = await ctx.covenant.isReviewer(target.id, ctx.wallet.wallet.address);
    if (!isReviewer) continue;

    const campaign = await ctx.covenant.getCampaign(target.id);
    if (!campaign.active || campaign.currentMilestone >= BigInt(campaign.milestoneCount)) continue;

    const milestone = await ctx.covenant.getMilestone(target.id, campaign.currentMilestone);
    if (Number(milestone.state) !== 1) continue; // 1 = Submitted

    const submissions = await ctx.covenant.getSubmissions(target.id, campaign.currentMilestone);
    const submissionIndex = submissions.length - 1;
    const already = await ctx.covenant.hasReviewed(
      target.id,
      campaign.currentMilestone,
      BigInt(submissionIndex),
      ctx.wallet.wallet.address,
    );
    if (already) continue;

    const approve = ctx.rng() < 0.85;
    const notes = approve ? "" : "Evidence insufficient for the stated acceptance criteria (synthetic rejection).";

    const outcome = await runWrite(
      () => ctx.covenant.connect(ctx.wallet.wallet).reviewProof(target.id, approve, notes),
      ctx.maxRetries,
    );
    recordWrite(ctx, "reviewProof", outcome);
    return; // one review action per turn is realistic
  }
}

// ---------------------------------------------------------------------------
// Read-only scenarios (all roles use these; read-only wallets use ONLY these)
// ---------------------------------------------------------------------------

export async function readScenario(ctx: ScenarioContext) {
  const reads: Array<() => Promise<unknown>> = [
    () => ctx.covenant.getAllCampaigns(),
    () => ctx.covenant.campaignCount(),
  ];

  if (ctx.world.campaigns.length > 0) {
    const target = pick(ctx.world.campaigns, ctx.rng);
    reads.push(
      () => ctx.covenant.getCampaign(target.id),
      () => ctx.covenant.getMilestones(target.id),
      () => ctx.covenant.getApprovalConfig(target.id),
      () => ctx.covenant.getDonors(target.id),
      () => ctx.covenant.refundOf(target.id, ctx.wallet.wallet.address),
      async () => {
        const campaign = await ctx.covenant.getCampaign(target.id);
        return ctx.covenant.trustScore(campaign.creator);
      },
    );
  }

  const read = pick(reads, ctx.rng);
  const outcome = await runRead(read);
  recordRead(ctx, "read", outcome);
}
